apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: hh2
type: Opaque
data:
  # MONGODB_USERNAME: c2VydmljZQ==
  # MONGODB_PASSWORD: WTc1a0hpckQ2TklUVHduWQ==
  # MONGODB_URL: Y2x1c3RlcjAud2N5d20ubW9uZ29kYi5uZXQ=
  MONGODB_CONNECTION_STRING: 